In [1]:
# Seeking to scrape each
import scrapy
from scrapy.crawler import CrawlerProcess
from scrapy.http import Request


class BirthdateSpider(scrapy.Spider):

    name = "Birthdate"
   
    # URL(s) to start with.
    start_urls = [
        'http://quotes.toscrape.com/author/Albert-Einstein/'
    ]
   

    # Use XPath to parse the response we get.
    def parse(self, response):
        new_urls=[]
        for pid in response.xpath('//div[@class="quote"]/span[2]/a/@href').extract():
                url = "http://quotes.toscrape.com{}".format(pid)
                new_urls.append(url)
                yield Request(url=new_urls, callback=self.parse)
        print(new_urls)
        # Iterate over every <author> element on the page.
        for i in new_urls:
            Request(url=new_urls[i])
        for article in response.xpath('//*'):
            # Yield a dictionary with the values we want.
            yield {
                # This is the code to choose what we want to extract
                # You can modify this with other Xpath expressions to extract other information from the site
                'Name': article.xpath('//div[@class="author-details"]/h3[@class="author-title"]/text()').extract_first(),
                'Date': article.xpath('//div[@class="author-details"]//span[@class="author-born-date"]/text()').extract_first(),
                'Location': article.xpath('//div[@class="author-details"]//span[@class="author-born-location"]/text()').extract_first(),
                'Text': article.xpath('//div[@class="author-description"]/text()').extract_first()
            }

# Tell the script how to run the crawler by passing in settings.
process = CrawlerProcess({
    'FEED_FORMAT': 'json',
    'FEED_URI': 'quotes.json',
    'USER_AGENT': 'ThinkfulDataScienceBootcampCrawler (thinkful.com)',
    'AUTOTHROTTLE_ENABLED': True,
    'HTTPCACHE_ENABLED': True,
    'LOG_ENABLED': False,
})

# Start the crawler with our spider.
process.crawl(BirthdateSpider)
process.start()
print('Success!')

[]
Success!

In [3]:
import pandas as pd
pd.read_json('quotes.json')

,Name,Date,Location,Text
0,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
1,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
2,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
3,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
4,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
5,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
6,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
7,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
8,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
9,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
10,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
11,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
12,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
13,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
14,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
15,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
16,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
17,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
18,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
19,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
20,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
21,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
22,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
23,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
24,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
25,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
26,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
27,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
28,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
29,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."
30,Albert Einstein\n,1879-03-14,"in Ulm, Germany","\n In 1879, Albert Einstein was born in..."